---
name: Test JMeter Action

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches: [master]

jobs:

  action_build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    steps:
      - uses: actions/checkout@v2
    
      - name: Run JMeter Action
      - uses: rbhadti94/apache-jmeter-action@v0.7.0

        with:
          testFilePath: Scripts/Peformance Bulk Inserts approach 3.jmx
          outputReportsFolder: ./
          args: "--loglevel INFO"
          plugins: "jpgc-casutg"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: ./

 

